import csv
import random

count = int(input("Plese enter the desired amount of accounts "))
passwd = str(input("Do you want the same password or different (Same = S / Different = D) "))


def print_info():
    print("First Name: ",first)
    print("Last Name: ",lastname)
    print("Password: ",password)
    print("Username: ",username,"\n\n")

with open("C:\\Temp\\gen-data.csv", "w",newline='') as csvFile: # May have to change the CSV save location
    field_headersd = ["first", "lastname", "username", "password"]
    writer = csv.DictWriter(csvFile,delimiter=",",fieldnames=field_headersd)
    writer.writeheader()
    if count > 0:
        for i in range(count):

            first_names=(
                'Andy',
                'Joe',
                "Sophia",
                "Olivia",
                "Emma",
                "Ava",
                "Aria",
                "Isabella",
                "Amelia",
                "Mia",
                "Riley",
                "Aaliyah",
                "Layla",
                "Zoe",
                "Charlotte",
                "Mila",
                "Harper",
                "Evelyn",
                "Camilla",
                "Eliana",
                "Chloe",
                "Lily",
                "Avery",
                "Luna",
                "Ella",
                "Adalyn",
                "Everly",
                "Leah",
                "Scarlett",
                "Aubrey",
                "Emily",
                "Maya",
                "Nora",
                "Ellie",
                "Madison",
                "Abigail",
                "Kinsley",
                "Isla",
                "Hannah",
                "Arianna",
                "Madelyn",
                "Paisley",
                "Elena",
                "Sarah",
                "Charlie",
                "Brooklyn",
                "Penelope",
                "Hailey",
                "Lila",
                "Callie",
                "Grace",
                "Emery",
                "Liam",
                "Jackson",
                "Noah",
                "Aiden",
                "Grayson",
                "Caden",
                "Lucas",
                "Elijah",
                "Oliver",
                "Muhammad",
                "Mason",
                "Carter",
                "Mateo",
                "Jayden",
                "Ethan",
                "Logan",
                "Sebastian",
                "James",
                "Alexander",
                "Benjamin",
                "Jacob",
                "Leo",
                "Josiah",
                "Daniel",
                "Julian",
                "Michael",
                "Jack",
                "Ryan",
                "Levi",
                "Jayce",
                "Wyatt",
                "Luke",
                "Owen",
                "Henry",
                "Caleb",
                "Gabriel",
                "William",
                "Isaiah",
                "Isaac",
                "David",
                "Matthew",
                "John",
                "Luca",
                "Lincoln",
                "Asher",
                "Cameron",
                "Ezra",
                "Nicholas",
                "Connor",
                "Colton")
            last_names=(
                'Johnson',
                'Smith',
                'Williams',
                "Smith",
                "Johnson",
                "Williams",
                "Brown ",
                "Jones",
                "Garcia ",
                "Miller",
                "Davis ",
                "Rodriguez",
                "Martinez",
                "Hernandez",
                "Lopez",
                "Gonzales",
                "Wilson",
                "Anderson",
                "Thomas",
                "Taylor",
                "Moore",
                "Jackson",
                "Martin",
                "Lee",
                "Perez",
                "Thompson",
                "White",
                "Harris",
                "Sanchez",
                "Clark",
                "Ramirez",
                "Lewis",
                "Robinson",
                "Walker",
                "Young",
                "Allen",
                "King",
                "Wright",
                "Scott",
                "Torres",
                "Nguyen",
                "Hill",
                "Flores",
                "Green",
                "Adams",
                "Nelson",
                "Baker",
                "Hall",
                "Rivera",
                "Campbell",
                "Mitchell",
                "Carter",
                "Roberts",
                "Gomez",
                "Phillips",
                "Evans",
                "Turner",
                "Diaz",
                "Parker",
                "Cruz",
                "Edwards",
                "Collins",
                "Reyes",
                "Stewart",
                "Morris",
                "Morales",
                "Murphy",
                "Cook",
                "Rogers",
                "Gutierrez",
                "Ortiz",
                "Morgan",
                "Cooper",
                "Peterson",
                "Bailey",
                "Reed",
                "Kelly",
                "Howard",
                "Ramos",
                "Kim",
                "Cox",
                "Ward",
                "Richardson",
                "Watson",
                "Brooks",
                "Chavez",
                "Wood",
                "James",
                "Bennet",
                "Gray",
                "Mendoza",
                "Ruiz",
                "Hughes",
                "Price",
                "Alvarez",
                "Castillo",
                "Sanders",
                "Patel",
                "Myers",
                "Long",
                "Ross",
                "Foster",
                "Jimenez")
            first = random.choice(first_names)
            lastname = random.choice(last_names)
            username = ''.join([first,".",lastname])

            if passwd.lower() == 'd':
                lower_chars = "abcdefghijklmnopqrstuvwxyz"
                upper_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                special = "!@#$%^&*()"
                num = "1234567890"
                password = ""
                for c in range(2): password += random.choice(lower_chars)+random.choice(upper_chars)+random.choice(num)+random.choice(special)
            else:
                password="vM1!aP5%"

            writer.writerow({"first":first,"lastname":lastname,"username":username,"password":password})

   
csvFile.close()
